spring.application.name=35-01-chashe-L2

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sbms
spring.datasource.username=root
spring.datasource.password=Rutvikbh@9960


spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# radis server is run on localhost with port number maintion here
spring.data.redis.host=localhost
spring.data.redis.port=6379
